### ISSUE TITLE
[DOCS] Update links to match new domain

### ISSUE THREAD

**Issue by Panquesito7** [Pradumnasaraf/candy#11]
### Description

There are a few links that are using the old website link (https://pradumnasaraf.github.io/candy).
However, the new link (https://pradumnasaraf.dev/candy) should be used instead.

The `README.md` file has two instances of these links, which should be updated.
Those can be found at line 22 and line 47.

Let us know if you need any help updating this! 🙂

**Comment by Pradumnasaraf** [comment]
Hey, 

Thanks for opening the issue. I have intentionally put that, so that, if ever my domain is down, the default one can still serve the docs and not affect the workflow :)

Closing it.
