### ISSUE TITLE
[FEATURE] Add a version command or flag

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/candy#13]
### Description

The command will out the current CLI version in the terminal

**Comment by Sindhuinti** [comment]
Hey @Pradumnasaraf  I like to work on this.
Do we need to make the version static or dynamically get the latest version from the github latest release?

**Comment by pmuls99** [comment]
Hey @Pradumnasaraf , I am interested in working for this feature. But there I dont think we have a Version file yet or we dont have a track for the same. Could provide details regarding the same.

**Comment by Pradumnasaraf** [comment]
Hey, 
Thanks for your interest. Then let's create a YAML file, with the version number, and with Viper we can get the number. What do you think?

Something like this:
//version.yml
```yml
version: 1.0.0
```

**Comment by pmuls99** [comment]
Hey @Pradumnasaraf , Have raised a PR, please inform for any further changes.

**Comment by Pradumnasaraf** [comment]
unassigning @pmuls99, no response from the contributor
