### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MadhuSaini22** [Pradumnasaraf/candy#19]
### Description

1. I just jumped to this repo as it's in Open Source projects from Pradumna's profile but here no where is written that it's Open Source. 
2. Need to add getting started guides so that if anyone wants to contribute to the projects then, they are refer the guide and easily contribute to the project.
3. Readme need to me more engaging so that new user doesn't feel overwhelming to contribute to the repo.

**Comment by Pradumnasaraf** [comment]
Closing this. Feel free to raise any new issues if you want.
