### ISSUE TITLE
[FEATURE] Feature to convert Key-Value pair to JSON

### ISSUE THREAD

**Issue by prateekjaindev** [Pradumnasaraf/candy#5]
### Description

Please add a feature to convert the Key-Value pair to JSON. An online [tool](https://amirch1.github.io/blog/text2json/index.html) is available for this, but it's not safe to use for confidential data.

**Comment by Pradumnasaraf** [comment]
Hey, @prateekjaindev. Thank you for opening the issue.

Yes, I agree with the security thing. For better clarity, the feature you requested is to convert the `=` key value to JSON (Screenshot)

<img width="1499" alt="Screenshot 2023-04-01 at 12 52 04 PM" src="https://user-images.githubusercontent.com/51878265/229272004-fbe84d26-4e69-46e2-9020-fab198c8f66d.png">

**Comment by prateekjaindev** [comment]
@Pradumnasaraf Yes Pradumna, This is exactly what I've requested.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Yes Pradumna, This is exactly what I've requested.

Thank you for the reply. The feature has been released 🥳. Please test it out and let me know your feedback.

You can download the latest version by using this command. 

```bash
go install github.com/Pradumnasaraf/candy@latest
```

Here are the docs on how to use it.

https://pradumnasaraf.dev/candy/#/pages/kvtj

> I am closing this issue to mark it as complete, but you can still comment.
